file <- read.table("household_power_consumption.txt", header = TRUE, sep= ";", na.strings = c("?",""))
file$Date <- as.Date(file$Date, format = "%d/%m/%Y")  
file$timetemp <- paste(file$Date, file$Time)
file$Time <- strptime(file$timetemp, format = "%Y-%m-%d %H:%M:%S")
fileset <- file[file$Time >= as.POSIXlt("2007-02-01") & file$Time < as.POSIXlt("2007-02-03"),]
par(mar=c(4,4,2,1),mfrow = c(2,2))
plot(fileset$Time,fileset$Global_active_power, type ="n",xlab="", ylab = "Global Active Power (kilowatts)")
lines(fileset$Time,fileset$Global_active_power)
plot(fileset$Time,fileset$Voltage, type ="n", xlab="datetime", ylab = "Voltage")
lines(fileset$Time,fileset$Voltage)
plot(fileset$Time,fileset$Sub_metering_1, type ="n",xlab="", ylab = "Energy sub metering")
lines(fileset$Time, fileset$Sub_metering_1, col = "black")
lines(fileset$Time, fileset$Sub_metering_2, col = "red")
lines(fileset$Time, fileset$Sub_metering_3, col = "blue")
legend("topright", lty= c(1,1), col= c("black","red","blue"), legend = c("Sub_metering_1","Sub_metering_2","Sub_metering_3"))
plot(fileset$Time,fileset$Global_reactive_power, type ="n", xlab="datetime", ylab = "Global_reactive_power")
lines(fileset$Time,fileset$Global_reactive_power)
dev.copy(png,file="plot4.png")
dev.off()